### ISSUE TITLE
my cat doesn't like it

### ISSUE THREAD

**Issue by tmmoa-iscte** [tmrbo-iscte/ES-LEI-2Sem-2022-Grupo-1#1]
please fix this horrible bug! My cat should be able to enjoy the web just like me. Could you support more cat-like fature? For example open a popup wich says "meowww" everytime I open a page while I throw my telephone to some animals. I saw yesterday a js framework that did this! Pleaseeeeee I need it now

**Comment by ambco-iscte** [comment]
meow purrr
